New Doc: Validation-and-Serialization
fastify/docs-chinese pull request #10
Opened 2018-06-20 09:21 UTC by fralonra

2018-06-21 00:49 UTC, vincent178 requested changes

2018-06-21 00:49 UTC, vincent178 commented on docs/Validation-and-Serialization.md
> +Fastify 使用基于模式 (schema) 的途径，从本质上将 schema 编译成了高性能的函数，来实现路由的验证与输出的序列化。我们推荐使用 [JSON Schema](http://json-schema.org/)，虽然这并非必要。
schema 后面没有翻译，第一句也可以不翻译，保持一致性。

2018-06-21 06:26 UTC, fralonra commented on docs/Validation-and-Serialization.md
> +Fastify 使用基于模式 (schema) 的途径，从本质上将 schema 编译成了高性能的函数，来实现路由的验证与输出的序列化。我们推荐使用 [JSON Schema](http://json-schema.org/)，虽然这并非必要。
确实没统一。我原先是想 shema 这类缺乏约定俗成翻译的单词，第一次出现时若提供了翻译，则后注英文，但之后均保留原文，表示之前的翻译仅作参考、帮助理解之用。

我觉得我们可以先确定一下，常见的概念如 scope, schema, response 等，哪些翻译，哪些保留原文，以及翻译成什么词。

2018-06-21 13:16 UTC, vincent178 commented on docs/Validation-and-Serialization.md
> +Fastify 使用基于模式 (schema) 的途径，从本质上将 schema 编译成了高性能的函数，来实现路由的验证与输出的序列化。我们推荐使用 [JSON Schema](http://json-schema.org/)，虽然这并非必要。
确实是，可以建立一个简单的翻译对照表，就列出常用的专业技术英文单词和对应的中文翻译。这边我觉得不合适主要是模式这个词不合适。`Fastify 使用基于模式的途径` 这句话基本上是看不懂的。

所以我的建议是这种不好翻译的专业性技术单词就可以保留。

你怎么看？

2018-06-21 14:32 UTC, fralonra commented on docs/Validation-and-Serialization.md
> +Fastify 使用基于模式 (schema) 的途径，从本质上将 schema 编译成了高性能的函数，来实现路由的验证与输出的序列化。我们推荐使用 [JSON Schema](http://json-schema.org/)，虽然这并非必要。
我目前不译的主要有以下几类 (有交叉)：
1. 原文中包裹于两个 \` 号之间的文本，和代码的文本相关联的 (例如：代码中出现的方法名、属性名等。例外：[Routes.md](https://github.com/fastify/docs-chinese/blob/master/docs/Routes.md) line 186 译文 `回调函数风格`，这里和代码文本无关，具有代码之外的实际含义)
2. Promise、async/await 等语法相关，约定俗成保留原文的
3. 包名、规范名等
4. 其他如：header、schema 等直译较难理解的专业术语

至于 `schema` 翻译成 `模式`，这个是有先例的，虽然这种译法几乎让人不知所云
权衡一下，我同意 `schema` 完全不译。

2018-06-22 00:12 UTC, vincent178 commented on docs/Validation-and-Serialization.md
> +Fastify 使用基于模式 (schema) 的途径，从本质上将 schema 编译成了高性能的函数，来实现路由的验证与输出的序列化。我们推荐使用 [JSON Schema](http://json-schema.org/)，虽然这并非必要。
我觉得你可以把这段话放到 Readme 里面，这些是所有翻译都要遵守的。

你可以把schame的翻译去掉，就可以merge了

2018-06-22 11:21 UTC, fralonra commented
已更新

2018-06-22 11:35 UTC, merged