Update: pr#1723
fastify/docs-chinese pull request #115
Opened 2019-07-15 14:04 UTC by fralonra

https://github.com/fastify/fastify/pull/1723

2019-07-15 14:05 UTC, fralonra commented on docs/Server.md
> +如果为 `false`，服务器会如常处理来访的请求。
这边需要确认下

2019-07-16 02:47 UTC, vincent178 requested changes

2019-07-16 02:47 UTC, vincent178 commented on docs/Server.md
> +如果为 `false`，服务器会如常处理来访的请求。
我建议翻译位 `服务器会正常处理请求` 我看了一下其他的关于 incoming request 也是直接翻译为请求。来访的请求有点拗口。

2019-07-18 01:08 UTC, vincent178 approved these changes

2019-07-18 12:25 UTC, merged