Update: pr#1770
fastify/docs-chinese pull request #122
Opened 2019-08-03 10:18 UTC by fralonra

https://github.com/fastify/fastify/pull/1770

2019-08-03 13:37 UTC, fralonra commented on docs/Serverless.md
> +添加一份如下的 `.dockerignore`，可以将构建所需的文件排除在容器之外 (能减小容器大小，加快构建速度)：
原文 `build artifacts`，翻译为：`构建所需的文件`。需要 check 一下。

2019-08-04 13:09 UTC, vincent178 commented on docs/Serverless.md
> +添加一份如下的 `.dockerignore`，可以将构建所需的文件排除在容器之外 (能减小容器大小，加快构建速度)：
句子有点歧义，是把不要构建的文件还是需要构建的文件。感觉是原文引起的，不是翻译的问题，你怎么看？

2019-08-04 13:40 UTC, fralonra commented on docs/Serverless.md
> +添加一份如下的 `.dockerignore`，可以将构建所需的文件排除在容器之外 (能减小容器大小，加快构建速度)：
确实有歧义，可以改为 `仅用于构建的文件`。

2019-08-04 21:29 UTC, vincent178 commented on docs/Serverless.md
> +添加一份如下的 `.dockerignore`，可以将构建所需的文件排除在容器之外 (能减小容器大小，加快构建速度)：
赞同这个翻译。

2019-08-04 21:30 UTC, vincent178 requested changes

2019-08-04 21:30 UTC, vincent178 commented on docs/Serverless.md
> +添加一份如下的 `.dockerignore`，可以将构建所需的文件排除在容器之外 (能减小容器大小，加快构建速度)：
`构建所需的文件` -> `仅用于构建的文件`

2019-08-05 12:40 UTC, fralonra commented on docs/Serverless.md
> +添加一份如下的 `.dockerignore`，可以将构建所需的文件排除在容器之外 (能减小容器大小，加快构建速度)：
已提交

2019-08-05 22:25 UTC, vincent178 approved these changes

2019-08-06 01:01 UTC, merged