New Doc: Write Plugin.md
fastify/docs-chinese pull request #33
Opened 2018-07-29 14:06 UTC by fralonra

2018-07-30 01:27 UTC, vincent178 requested changes

2018-07-30 01:27 UTC, vincent178 commented on docs/Write-Plugin.md
> +Fastify 运用了不同的技术来优化代码，其大部分都被写入了文档。我们强烈建议你阅读[插件指南](https://github.com/fastify/fastify/blob/master/docs/Plugins-Guide.md)一文，以了解所有可用于构建插件的 API 及其用法。
url 不对。

2018-07-30 14:05 UTC, fralonra commented on docs/Write-Plugin.md
> +Fastify 运用了不同的技术来优化代码，其大部分都被写入了文档。我们强烈建议你阅读[插件指南](https://github.com/fastify/fastify/blob/master/docs/Plugins-Guide.md)一文，以了解所有可用于构建插件的 API 及其用法。
多谢，已修正

2018-07-31 02:30 UTC, vincent178 approved these changes

2018-07-31 02:30 UTC, merged